# Generated by Django 5.1.7 on 2025-03-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drink',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
