# Generated by Django 5.1.7 on 2025-03-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkerApp', '0002_alter_drink_dislikes_alter_drink_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='complexity',
            field=models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex')], default='simple', max_length=10),
        ),
        migrations.AddField(
            model_name='drink',
            name='strength',
            field=models.CharField(choices=[('non-alcoholic', 'Non-Alcoholic'), ('light', 'Light'), ('medium', 'Medium'), ('strong', 'Strong')], default='non-alcoholic', max_length=15),
        ),
        migrations.AddField(
            model_name='drink',
            name='taste_type',
            field=models.CharField(choices=[('sweet', 'Sweet'), ('bitter', 'Bitter'), ('sour', 'Sour'), ('salty', 'Salty'), ('umami', 'Umami')], default='sweet', max_length=10),
        ),
        migrations.AddField(
            model_name='drink',
            name='temperature',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('warm', 'Warm')], default='cold', max_length=10),
        ),
    ]
