# Generated by Django 5.1.7 on 2025-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkerApp', '0004_drink_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='short_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
